# 跳过构建在Commit Message中添加 [CI SKIP]
kind: pipeline
name: 打包部署[NodeJs-Npm]

clone:
  disable: true

steps:
  - name: 下载源代码[Git]
    image: docker:git
    commands:
      - echo "### $DRONE_GIT_HTTP_URL -> $DRONE_BRANCH"
      - git clone http://192.168.31.5:13000/lizw/ant-design-pro.git ./
      - git checkout base-2.x
      # - git clone $DRONE_GIT_HTTP_URL ./
      # - git checkout $DRONE_BRANCH

  - name: 编译源代码[Npm]
    image: node:10.15.2-alpine
    volumes:
      - name: package-nodejs
        path: /package-nodejs
    commands:
      - npm config set unsafe-perm true
      - npm config set cache "/package-nodejs/npm-cache"
      - npm config set prefix "/package-nodejs/npm"
      - npm config set registry https://registry.npm.taobao.org --global
      - npm config set disturl https://npm.taobao.org/dist --global
      - npm install --prefer-offline
      # # prod打包文件输出
      # - npm run build-prod
      # - mv dist/ server/
      # - cd server
      # - npm install --prefer-offline
      # # 把打包好的文件移动到硬盘上
      # - rm -rf /package-nodejs/prod
      # - mkdir -p /package-nodejs/prod
      # - cp -a -r -f ./ /package-nodejs/prod
      # - rm -rf dist/
      # - cd ../
      # dev打包
      - npm run build-proxy
      - mv dist/ server/
      - cd server
      - npm install --prefer-offline

  - name: 构建镜像[Docker]
    image: plugins/docker
    settings:
      registry: '192.168.31.5:15000'
      repo: '192.168.31.5:15000/nodejs-service/ant-design-pro'
      # bip: true
      insecure: true
      dockerfile: ./Dockerfile
      target: dev
      tags: ['0.0.1-SNAPSHOT']
      force_tag: true
      auto_tag: false
      auto_tag_suffix: ''

  - name: 启动容器[SSH-Docker]
    image: appleboy/drone-ssh
    settings:
      host: 192.168.31.5
      port: 22
      username:
        from_secret: sshUsername
      password:
        from_secret: sshPassword
      command_timeout: 300s
      script:
        - echo "------------------< 停止容器 >------------------"
        - docker stop ant-design-pro
        - echo "------------------< 删除容器 >------------------"
        - docker rm -v ant-design-pro
        - echo "------------------< 删除旧镜像 >------------------"
        - docker rmi 192.168.31.5:15000/nodejs-service/pant-design-pro:0.0.1-SNAPSHOT
        - echo "------------------< 拉取新镜像 >------------------"
        - docker pull 192.168.31.5:15000/nodejs-service/ant-design-pro:0.0.1-SNAPSHOT
        - echo "------------------< 运行新镜像 >------------------"
        - docker run --name ant-design-pro -d -p 19080:9066 192.168.31.5:15000/nodejs-service/ant-design-pro:0.0.1-SNAPSHOT
        - exit

  - name: 发送通知[Email]
    image: drillster/drone-email
    # detach: true
    commands:
      - date
      - cd /etc
      - cp /share/localtime ./
      - date
      - cd /bin
      - ./drone-email
    volumes:
      - name: share
        path: /share
    settings:
      host: smtp.qq.com
      port: 465
      username:
        from_secret: emailUsername
      password:
        from_secret: emailPassword
      skip_verify: false
      from:
        from_secret: emailUsername
      recipients: [ 'lzw1000000@163.com' ]
      recipients_only: false
      subject: '[#{{build.number}}-{{build.status}}] {{repo.name}}'
      body: 'file:///drone/src/drone-email.html'

volumes:
  # 共享文件
  - name: share
    host:
      path: /home/lizw/Desktop/docker-opt/share
  # nodejs打包目录
  - name: package-nodejs
    host:
      path: /home/lizw/Desktop/docker-opt/package/nodejs

# -------------------------------------------------------------------------------------------------------------
